import type { Metadata } from "next";
import "./globals.css";
<<<<<<< HEAD
import { Header } from "@/components";


export const metadata = {
  title: "Skelv",
  description: "Get Hired, Gain Experience, Build Your Portfolio.",
  icons: 'globe.svg',
  other: {
    "stylesheet":"https://prod-waitlist-widget.s3.us-east-2.amazonaws.com/getwaitlist.min.css",
  }
=======


export const metadata: Metadata = {
  title: "Skelv",
  description: "Generated by create next app",
  icons: 'globe.svg',
>>>>>>> f52cc9f (first commit)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className=""
      >
<<<<<<< HEAD
        <Header/>
=======
>>>>>>> f52cc9f (first commit)
        {children}
      </body>
    </html>
  );
}
